### ISSUE TITLE
Shows user signed in on the Google search page

### ISSUE THREAD

**Issue by neekt** [DaAwesomeP/Searchonymous2#1] opened 2017-06-15 09:26 UTC
This extension doesn't appear to work - it still shows me as signed in on the Google search page. Is this intentional, or is the extension not working? If it's intentional it should be made clear, because it is different behaviour to the original Searchonymous.

I appreciate your efforts to port this to WebExtensions (and, by default, making it e10s compatible).

**Comment by DaAwesomeP** [comment] 2017-06-19 12:45
Hi,
That is not intentional. Would you mind providing the URL that you see this with (just search "test" or something) and your Firefox version and operating system? I have a feeling that Google has a new URL scheme that is not being caught to trigger the addon.

> I appreciate your efforts to port this to WebExtensions (and, by default, making it e10s compatible).

You're welcome! I'm slowly working my way through porting them over.

**Comment by neekt** [comment] 2017-06-19 16:20
I'm seeing it on the Google home page, even before doing a search. I just tested it on both macOS Sierra and Windows 8 using FF 54.0, including with a FF refresh, and it was the same deal. The original Searchonymous still seems to be doing the job, but it disables multiprocess windows (not e10s compatible) so I've disabled it.

E.g. URL: https://www.google.com/search?q=test&ie=utf-8&oe=utf-8&client=firefox-b

**Comment by DaAwesomeP** [comment] 2017-06-20 04:50
I cannot reproduce the issue. Please go to `about:debugging` and click `Debug` on the addon. Then open a Google search and see if any errors appear in the console.

**Comment by neekt** [comment] 2017-06-20 05:23
Here's the console output when I do a Google search:

          Content Security Policy: The page's settings blocked the loading
of a resource at self ("script-src 'nonce-qJne4F4QBTPtSTnxSWzUxhqOTGc'
'unsafe-inline' 'strict-dynamic' https: http: 'unsafe-eval'"). Source:
onsubmit attribute on DIV element. widget
Content Security Policy: The page's settings blocked the loading of a
resource at self ("script-src 'nonce-qJne4F4QBTPtSTnxSWzUxhqOTGc'
https://notifications.google.com 'unsafe-eval' https://apis.google.com
https://ssl.gstatic.com https://www.google.com https://www.gstatic.com").
Source: onsubmit attribute on DIV element. widget
Content Security Policy: The page's settings blocked the loading of a
resource at self ("script-src 'nonce-qJne4F4QBTPtSTnxSWzUxhqOTGc'
'unsafe-inline' 'strict-dynamic' https: http: 'unsafe-eval'"). Source:
onchange attribute on DIV element. widget
Content Security Policy: The page's settings blocked the loading of a
resource at self ("script-src 'nonce-qJne4F4QBTPtSTnxSWzUxhqOTGc'
https://notifications.google.com 'unsafe-eval' https://apis.google.com
https://ssl.gstatic.com https://www.google.com https://www.gstatic.com").
Source: onchange attribute on DIV element. widget
Content Security Policy: The page's settings blocked the loading of a
resource at self ("script-src 'nonce-qJne4F4QBTPtSTnxSWzUxhqOTGc'
'unsafe-inline' 'strict-dynamic' https: http: 'unsafe-eval'"). Source:
onfocusin attribute on DIV element. widget
Content Security Policy: The page's settings blocked the loading of a
resource at self ("script-src 'nonce-qJne4F4QBTPtSTnxSWzUxhqOTGc'
https://notifications.google.com 'unsafe-eval' https://apis.google.com
https://ssl.gstatic.com https://www.google.com https://www.gstatic.com").
Source: onfocusin attribute on DIV element. widget
[Exception... "Component returned failure code: 0x80070057
(NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.loadSheetUsingURIString]"
nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame ::
resource://gre/modules/ExtensionUtils.jsm :: runSafeSyncWithoutClone ::
line 71"  data: no]  (unknown)
[Exception... "Component returned failure code: 0x80070057
(NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.loadSheetUsingURIString]"
nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame ::
resource://gre/modules/ExtensionUtils.jsm :: runSafeSyncWithoutClone ::
line 71"  data: no]

**Comment by DaAwesomeP** [comment] 2017-09-26 02:24
Closing; bug is unconfirmed. There is possibly another extension interfering. There have been no other reports on GitHub or AMO.

**Closed as completed by DaAwesomeP** 2017-09-26 02:24 UTC
Labels: bug
